services:
  basic_example:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_UID=${UID:-1000}
        - HOST_GID=${GID:-1000}
    image: nc_basic_example:0.0.1
    container_name: basic_example
    privileged: true
    network_mode: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${HOME}:${HOME}
    working_dir: ${CURRENT_DIR}
    environment:
      - HOST_UID=${UID:-1000}
      - HOST_GID=${GID:-1000}
      - DISPLAY=${DISPLAY:-:0}
      - HOME=${HOME}
    stdin_open: true
    tty: true
    command: sleep infinity
